services:

  moonlander:
    image: 54ik1/moonlander-compose:latest
    container_name: Moonlander
    ports:
      - 8008:8008
    volumes:
      - ./plugins:/app/plugins
      - ./storge:/app/storge
      - ./conf.d:/app/conf.d
    restart: unless-stopped
